# Generated by Django 2.1.12 on 2022-11-09 08:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, max_length=200)),
                ('total_price', models.IntegerField(default=0, max_length=200)),
            ],
            options={
                'verbose_name': 'carts',
                'verbose_name_plural': 'carts',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='OrderCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'order_company',
                'verbose_name_plural': 'order_company',
                'db_table': 'order_company',
            },
        ),
        migrations.CreateModel(
            name='OrderDtails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, max_length=200)),
                ('total_money', models.IntegerField(default=0, max_length=200)),
            ],
            options={
                'verbose_name': 'order_details',
                'verbose_name_plural': 'order_details',
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'AWAITING_PAYMENT'), (1, 'AWAITING_CHECK'), (2, 'AWAITING_SHIPPING'), (3, 'SHIPPING'), (4, 'SHIPPED'), (5, 'CUSTOMER_CHECK'), (6, 'COMPILED'), (7, 'CANCEL')], default=0)),
                ('all_money', models.IntegerField(default=0, max_length=200)),
                ('payment', models.SmallIntegerField(choices=[(0, 'CHECKOUT'), (1, 'INSTORE'), (2, 'CARD'), (3, 'APP')], default=0)),
            ],
            options={
                'verbose_name': 'orders',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(default='unkown sku', max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(default='unkown image', max_length=200)),
                ('type', models.SmallIntegerField(choices=[(0, 'DIGITAL'), (1, 'PHYSICAL')], default=0)),
                ('categories', models.CharField(default='unkown categories', max_length=200)),
                ('price', models.IntegerField(default=0, max_length=200)),
                ('number', models.IntegerField(default=0, max_length=200)),
                ('visible', models.BooleanField(default=True)),
                ('description', models.TextField(default='this is a description')),
            ],
            options={
                'verbose_name': 'products',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('address', models.CharField(default='unkown adress', max_length=200)),
                ('resume', models.TextField(default='this is resume', max_length=200)),
            ],
            options={
                'verbose_name': 'user_company',
                'verbose_name_plural': 'user_company',
                'db_table': 'user_company',
            },
        ),
        migrations.CreateModel(
            name='UserCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('age', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('address', models.CharField(default='unkown address', max_length=200)),
                ('gender', models.SmallIntegerField(choices=[(0, 'FEMAIL'), (1, 'MAIL'), (2, 'UNKONWN')], default=2)),
            ],
            options={
                'verbose_name': 'user_customer',
                'verbose_name_plural': 'user_customer',
                'db_table': 'user_customer',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_products', to='users.UserCompany'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='users.UserCustomer'),
        ),
        migrations.AddField(
            model_name='orderdtails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdtails_dtails', to='users.Orders'),
        ),
        migrations.AddField(
            model_name='orderdtails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdtails_product', to='users.Products'),
        ),
        migrations.AddField(
            model_name='ordercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercompany_company', to='users.UserCompany'),
        ),
        migrations.AddField(
            model_name='ordercompany',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercompany_order', to='users.Orders'),
        ),
        migrations.AddField(
            model_name='ordercompany',
            name='orderdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercompany_orderdetail', to='users.OrderDtails'),
        ),
        migrations.AddField(
            model_name='carts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_carts', to='users.Products'),
        ),
        migrations.AddField(
            model_name='carts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_carts', to='users.UserCustomer'),
        ),
    ]
