# Generated by Django 2.1.12 on 2022-11-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='number',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='carts',
            name='total_price',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='orderdtails',
            name='number',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='orderdtails',
            name='total_money',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='all_money',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='number',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
